---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product name: chef

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config: 
      run_command: /usr/lib/systemd/systemd
      privileged: true
      privision_command:
        - systemctl enable sshd.service
suites:
  - name: default
    run_list:
      - recipe[nt_nginx::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
